# **텐서(Tensor)**

텐서는 배열이나 행렬과 매우 유사한 특수한 자료구조입니다. 파이토치에서는 텐서를 사용하여 모델의 입력과 출력, 그리고 모델의 매개변수들을 encode(부호화)합니다. 

텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 장점 외에는 numpy에 ndarray와 유사합니다. 실제로 텐서와 numpy 배열은 종종 동일한 내부 메모리를 공유할 수 있기에 데이터를 복사할 필요가 없습니다. 텐서는 또한 자동 미분에 최적화되어 있습니다. 

In [1]:
import torch
import numpy as np

## **텐서 초기화**

텐서는 여러가지 방법으로 초기화할 수 있습니다. 


**데이터로부터 직접 생성하기**

데이터로부터 직접 텐서를 생성할 수 있습니다. 데이터의 자료형은 자동으로 유추합니다.

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

**numpy 배열로부터 생성하기**

텐서는 numpy 배열로부터 생성할 수도 있습니다. 그리고 그 반대도 가능합니다.

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**다른 텐서로부터 생성하기**

명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(shape, datatype)을 유지합니다.

In [4]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7057, 0.6133],
        [0.6246, 0.5104]]) 



**random 또는 constant 값 사용하기**

shape는 텐서의 차원을 나타내는 튜플로 아래 함수들에서는 출력 텐서의 차원을 결정합니다.

In [7]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5007, 0.4764, 0.3961],
        [0.3265, 0.1327, 0.1978]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


---

## **텐서의 속성**

텐서의 속성은 shape와 datatype 및 어느 장치에 저장되는지를 나타냅니다.

In [8]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


---

## **텐서의 연산**

전치, 인덱싱, 슬라이싱, 계산 등 여러가지 연산들은 [여기](https://pytorch.org/docs/stable/torch.html)에서 확인할 수 있습니다.

각 연산들은 일반적으로 GPU에서 실행할 수 있습니다. 그러나 기본적으로 텐서는 CPU에 생성됩니다. 그렇기에 .to 메소드를 사용하여 GPU로 텐서를 명시적으로 이동시켜야 GPU에서 사용할 수 있습니다. 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이 든다는 것을 명심해야 합니다.

In [10]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor = tensor.to(device)

**Numpy 식의 표준 인덱싱과 슬라이싱**

In [11]:
tensor = torch.ones(4, 4)
print("First row:", tensor[0])
print("First column:", tensor[:, 0])
print("Last row:", tensor[..., -1])
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last row: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**텐서 합치기**

torch.cat을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있습니다. torch.stack은 torch.cat과 미묘하게 다릅니다.

In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1, t1.shape)

t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2, t2.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) torch.Size([4, 12])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]]) torch.Size([4, 3, 4])


**산술 연산**

In [14]:
# 두 텐서 간의 행렬 곱을 계산합니다. 
# y1 = y2 = y3
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# 요소별 곱을 계산합니다.
# z1 = z2 = z3
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**단일 요소 텐서**

텐서의 모든 값을 하나로 집계하여 요소가 하나인 텐서의 경우, item()을 사용하여 python 숫자 값으로 변환할 수 있습니다.

In [15]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**바꿔치기 연산**

연산 결과를 피연산자에 저장하는 연산을 바꿔치기 연산이라고 합니다. _ 접미사를 갖습니다. 예를 들어 x_copy_(y)나 x.t_()는 x를 변경합니다.

In [16]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


바꿔치기 연산은 메모리를 일부 절약하지만, 기록이 즉시 삭제되어 도함수 계산에 문제가 될 수 있습니다. 그렇기에 권장되지는 않습니다.

---

## **Numpy 변환**

cpu 상의 텐서와 numpy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

**텐서를 numpy 배열로 변환하기**

In [17]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 numpy에도 적용됩니다.

In [18]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**Numpy 배열을 텐서로 변환하기**

In [19]:
n = np.ones(5)
t = torch.from_numpy(n)

numpy 배열의 변경 사항 역시 텐서에 반영됩니다.

In [20]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
